import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
//import {Providers} from "./providers"

const edSansMedium = localFont({
  src:'../public/fonts/EverydaySans-Medium-Web.woff2',
  display:'swap',
  variable:'--font-edmedium'
})
const edSansBold = localFont({
  src:'../public/fonts/EverydaySans-Bold-Web.woff2',
  display:'swap',
  variable:'--font-edbold'
})
const creakingCrypt = localFont({
  src:'../public/fonts/CreakingCrypt-Regular.woff2',
  display:'swap',
  variable:'--font-creaking'
})

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
         className={`${edSansBold.className} font-edbold antialiased`}
      >
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${edSansBold.className}`}
      >
        {children}
      </body>
    </html>
  );
}
