/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

//import React, { useRef } from 'react'
//import { useGLTF } from '@react-three/drei'

export function CompTest(props) {
 // const { nodes, materials } = useGLTF('/first_mut.glb')
  return (
    <div className="bg-green-200">
      <p> ayyyy </p>
    </div>

  )
}

export default CompTest
//useGLTF.preload('/first_mut.glb')
