/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
https://gltf.pmnd.rs/
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/first_mut.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        scale={[37.5, 1, 37.5]}
        position={[0,0,0]}
        rotation-x={Math.PI / 2}
      >
      <meshStandardMaterial color="green"/>
      </mesh>

    </group>
  )
}

useGLTF.preload('/first_mut.glb')

export default Model

/*
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        scale={[37.5, 1, 37.5]}
        position={[0,0,0]}
        rotation-x={Math.PI / 2}
      />
*/